services:
  - type: web
    name: translator-media-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: BOT_TOKEN
        sync: false
    autoDeploy: true
    plan: free
    runtime: python
    region: oregon
    pythonVersion: 3.11.0
    healthCheckPath: /healthz
    healthCheckTimeoutSeconds: 15

